name = "Asalith Fields"
author = "PerlandDev"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31aa7ed7f25ed0d50537981a4a6d35d1399f46aef6dabaa6a1f7ee73142ed1b6"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
datapack-folder = "./datapacks"
