name = "Asalith Fields"
author = "PerlandDev"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d3ce4e1ecaffd4cc33be7f072631040ba56a139de327253931a76604d0a588a"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
datapack-folder = "./datapacks"
