name = "Asalith Fields"
author = "PerlandDev"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e4544b2c4cb01c3a6d9db32f1a38ea0823f6174d2fec0872a12df85351ec1ee"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
datapack-folder = "./datapacks"
